### ISSUE TITLE
Adding 1mio macs- Crashes

### ISSUE THREAD

**Issue by tunay87** [Evilvir-us/MacAttack#10]
Thank you for your updates. If I insert a large number of Macs manually the program crashes and does not respond.
Would it be possible to select a file via Explorer?

Thank you very much for your efforts.

**Comment by Evilvir-us** [comment]
Yes, this is possible, not difficult to do, and will be our only option for handling large lists, as PyQt struggles with managing large amounts of text in text boxes. This is also why I previously set a buffer to limit the total number of lines in the output box. We should be able to read the file into a dictionary or list, then use the macs sequential, or at random, and remove them from the dictionary after successful use. I'll likely implement this method sometime this week.

**Comment by Evilvir-us** [comment]
Completed
