### ISSUE TITLE
Feature Request: Display Current Version Number and Notify Users of Updates

### ISSUE THREAD

**Issue by ravigaonly** [Evilvir-us/MacAttack#3]
Thank you for the great work on this project! I have a feature suggestion that could enhance the user experience:

**Display Current Version Number:**
It would be helpful if the app displayed the current version number somewhere accessible, such as in the settings page. This allows users to easily verify which version they are using.

**Notify Users of New Versions:**
Adding a feature to notify users when a new version is available for download would ensure they stay up to date with the latest features and fixes.

These additions would improve usability and keep the users more engaged with the latest updates.

Thank you for considering these suggestions!

**Comment by Evilvir-us** [comment]
Ok, good idea, this is very easy to implement, will add when I have time and release with next update. Busy with work this week.

**Comment by Evilvir-us** [comment]
I've implemented the update check/notification. When the program is launched, a window will pop up if a new version is available. It will show the current version and the new version, and offer a link to the releases page. This check can be disabled in the settings tab. However, I haven't added the visible version number to the app yet. I'll make sure to include the version number label in the settings tab on the next release.

**Comment by Evilvir-us** [comment]
Request complete: The program now checks the version at startup, and version information is available in the Settings tab.
