### ISSUE TITLE
add an option

### ISSUE THREAD

**Issue by Jack-the-Ripper-district-londonien-1888** [Evilvir-us/MacAttack#6]
would it be possible to have the choice between our own mac or random list ?

**Comment by Evilvir-us** [comment]
I can make this happen by adding an option to use a custom list of MAC addresses in a box, similar to the proxy list box. To avoid rewriting a lot of code because I’m lazy, the MAC addresses would be selected randomly instead of sequentially. Once a MAC address returns a result, it wouldn’t be used again for the current session. I'll aim to tackle this sometime next week.

**Comment by rehanmumtaz** [comment]
> I can make this happen by adding an option to use a custom list of MAC addresses in a box, similar to the proxy list box. To avoid rewriting a lot of code because I’m lazy, the MAC addresses would be selected randomly instead of sequentially. Once a MAC address returns a result, it wouldn’t be used again for the current session. I'll aim to tackle this sometime next week.

yes please do that <3 it would be killer then

**Comment by rehanmumtaz** [comment]
I also wanted to ask , when we click "stop scan" does it pause or stop ? I mean if i start it again would it start scanning the old already scanned mac addresses again ? 
thanks

**Comment by Evilvir-us** [comment]
The program doesn't use a list of MAC addresses because there are over 16.7 million possible MAC addresses starting with 00:1A:79:. Whether you start or stop, it doesn't matter; each time a MAC address is checked, it is simply randomly generated from that pool of 16.7 million.

**Comment by Evilvir-us** [comment]
Request Completed in v4.4.1

**Comment by Evilvir-us** [comment]
Sorry, I think I broke something in the release. I will look into it after work.

**Comment by rehanmumtaz** [comment]
> Owner

thank you so much for your efforts , really appreciate that you are working in Christmas holidays :P

**Comment by Evilvir-us** [comment]
This method will be changing to a text file soon. https://github.com/Evilvir-us/MacAttack/issues/10
