### ISSUE TITLE
An option

### ISSUE THREAD

**Issue by rehanmumtaz** [Evilvir-us/MacAttack#8]
Hello, I just wanted to ask many if possible could you add proxy testing option for our custom proxies as well , like your software test proxies which it scraps on its own,

thanks

**Comment by Evilvir-us** [comment]
That's an excellent suggestion! I'll definitely look into implementing it as soon as I have some time. In fact, I was already planning to rework the proxy checker, so this fits perfectly with that update. Thanks for the input!

**Comment by Evilvir-us** [comment]
A button has been added next to the "Get Proxies" button, allowing you to test any proxies already entered in the text box.
